### ISSUE TITLE
Confused about native app authentication

### ISSUE THREAD

**Issue by s0nspark** [jasonjoh/office365-azure-guides#1]
I am wanting to create a native app (a ruby script, in particular) to manage entries on our organization's shared calendar but am rather confused about how exactly to implement the authentication and what ramifications oauth2 will have on the app.

I would like to have this app scheduled to run unattended and "automatically" authenticate with my credentials if necessary - is that possible?

**Comment by jasonjoh** [comment]
For an unattended scenario, you would want to look at the client credentials OAuth2 flow. How this would work is that an administrator would grant consent one time to the app, and then it would have access to all mailboxes in the organization. Here's a blog post on it: http://blogs.msdn.com/b/exchangedev/archive/2015/01/21/building-demon-or-service-apps-with-office-365-mail-calendar-and-contacts-apis-oauth2-client-credential-flow.aspx. I also have a sample app in Python here: https://github.com/jasonjoh/python_clientcred

**Comment by s0nspark** [comment]
Thanks! I believe that sets me on the right path :)
